<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CoaSeeder extends Seeder
{
    public function run()
    {
        DB::table('coa')->insert([
             ['id_coa'=>1,'coa_name'=>'Aset','coa_number'=>'1.0.00','posisi_awal'=>null],
    ['id_coa'=>2,'coa_name'=>'Aset Lancar','coa_number'=>'1.1.00','posisi_awal'=>null],
    ['id_coa'=>5,'coa_name'=>'Kas','coa_number'=>'1.1.01','posisi_awal'=>null],
    ['id_coa'=>6,'coa_name'=>'Kas Besar','coa_number'=>'1.1.01.01','posisi_awal'=>'Debit'],
    ['id_coa'=>8,'coa_name'=>'Kas Kecil','coa_number'=>'1.1.01.02','posisi_awal'=>'Debit'],
    ['id_coa'=>261,'coa_name'=>'Kas Operasional','coa_number'=>'1.1.01.03','posisi_awal'=>'Debit'],
    ['id_coa'=>280,'coa_name'=>'Kas Besar 2','coa_number'=>'1.1.01.04','posisi_awal'=>'Debit'],
    ['id_coa'=>287,'coa_name'=>'Kas Direksi','coa_number'=>'1.1.01.99','posisi_awal'=>'Debit'],
    ['id_coa'=>9,'coa_name'=>'Bank','coa_number'=>'1.1.02','posisi_awal'=>null],
    ['id_coa'=>10,'coa_name'=>'BCA - XXX','coa_number'=>'1.1.02.01','posisi_awal'=>'Debit'],
    ['id_coa'=>238,'coa_name'=>'BCA -YYY','coa_number'=>'1.1.02.04','posisi_awal'=>'Debit'],
    ['id_coa'=>239,'coa_name'=>'Common -','coa_number'=>'1.1.02.05','posisi_awal'=>'Debit'],
    ['id_coa'=>262,'coa_name'=>'OCBC NISP','coa_number'=>'1.1.02.06','posisi_awal'=>'Debit'],
    ['id_coa'=>208,'coa_name'=>'BCA -BDN','coa_number'=>'1.1.02.08','posisi_awal'=>'Debit'],
    ['id_coa'=>237,'coa_name'=>'BCA - LY','coa_number'=>'1.1.02.09','posisi_awal'=>'Debit'],
    ['id_coa'=>17,'coa_name'=>'Piutang','coa_number'=>'1.1.03','posisi_awal'=>null],
    ['id_coa'=>18,'coa_name'=>'Piutang Usaha','coa_number'=>'1.1.03.01','posisi_awal'=>'Debit'],
    ['id_coa'=>19,'coa_name'=>'Piutang Karyawan','coa_number'=>'1.1.03.02','posisi_awal'=>'Debit'],
    ['id_coa'=>168,'coa_name'=>'Piutang Direksi','coa_number'=>'1.1.03.03','posisi_awal'=>'Debit'],
    ['id_coa'=>169,'coa_name'=>'Piutang Uang Jalan','coa_number'=>'1.1.03.04','posisi_awal'=>'Debit'],
    ['id_coa'=>170,'coa_name'=>'Piutang Lain-lain','coa_number'=>'1.1.03.05','posisi_awal'=>'Debit'],
    ['id_coa'=>264,'coa_name'=>'Deposit/Jaminan Kendaraan','coa_number'=>'1.1.03.06','posisi_awal'=>'Debit'],
    ['id_coa'=>20,'coa_name'=>'Investasi Jangka Pendek','coa_number'=>'1.1.04','posisi_awal'=>null],
    ['id_coa'=>266,'coa_name'=>'Deposito','coa_number'=>'1.1.04.01','posisi_awal'=>'Debit'],
    ['id_coa'=>21,'coa_name'=>'Persediaan','coa_number'=>'1.1.05','posisi_awal'=>null],
    ['id_coa'=>22,'coa_name'=>'Persediaan Sparepart','coa_number'=>'1.1.05.01','posisi_awal'=>'Debit'],
    ['id_coa'=>171,'coa_name'=>'Persediaan Kantor','coa_number'=>'1.1.05.02','posisi_awal'=>'Debit'],
    ['id_coa'=>24,'coa_name'=>'Pajak Dibayar Dimuka','coa_number'=>'1.1.07','posisi_awal'=>null],
    ['id_coa'=>25,'coa_name'=>'Pajak PPN Masukan','coa_number'=>'1.1.07.01','posisi_awal'=>'Debit'],
    ['id_coa'=>26,'coa_name'=>'PPh 21 Dibayar Dimuka','coa_number'=>'1.1.07.02','posisi_awal'=>'Debit'],
    ['id_coa'=>27,'coa_name'=>'PPh 22 Dibayar Dimuka','coa_number'=>'1.1.07.03','posisi_awal'=>'Debit'],
    ['id_coa'=>28,'coa_name'=>'PPh 23 Dibayar Dimuka','coa_number'=>'1.1.07.04','posisi_awal'=>'Debit'],
    ['id_coa'=>29,'coa_name'=>'PPh 25 Dibayar Dimuka','coa_number'=>'1.1.07.05','posisi_awal'=>'Debit'],
    ['id_coa'=>30,'coa_name'=>'Pajak Lebih Bayar','coa_number'=>'1.1.07.06','posisi_awal'=>'Debit'],
    ['id_coa'=>174,'coa_name'=>'PPh 4(2) Dibayar Dimuka','coa_number'=>'1.1.07.07','posisi_awal'=>'Debit'],
    ['id_coa'=>31,'coa_name'=>'Biaya Dibayar Dimuka','coa_number'=>'1.1.08','posisi_awal'=>null],
    ['id_coa'=>32,'coa_name'=>'Asuransi Dibayar Dimuka','coa_number'=>'1.1.08.01','posisi_awal'=>'Debit'],
    ['id_coa'=>34,'coa_name'=>'Uang Muka Pembelian','coa_number'=>'1.1.08.03','posisi_awal'=>'Debit'],
    ['id_coa'=>175,'coa_name'=>'Sewa Dibayar Dimuka','coa_number'=>'1.1.08.04','posisi_awal'=>'Debit'],
    ['id_coa'=>176,'coa_name'=>'Biaya Dibayar Dimuka - HPP','coa_number'=>'1.1.08.05','posisi_awal'=>'Debit'],
    ['id_coa'=>36,'coa_name'=>'Cadangan Piutang Tak Tertagih','coa_number'=>'1.1.09.01','posisi_awal'=>'Kredit'],
    ['id_coa'=>37,'coa_name'=>'Aset Tidak Lancar','coa_number'=>'1.2.00','posisi_awal'=>null],
    ['id_coa'=>39,'coa_name'=>'Tanah','coa_number'=>'1.2.01.01','posisi_awal'=>'Debit'],
    ['id_coa'=>40,'coa_name'=>'Bangunan Kantor','coa_number'=>'1.2.01.02','posisi_awal'=>'Debit'],
    ['id_coa'=>41,'coa_name'=>'Kendaraan','coa_number'=>'1.2.01.03','posisi_awal'=>'Debit'],
    ['id_coa'=>42,'coa_name'=>'Mesin','coa_number'=>'1.2.01.04','posisi_awal'=>'Debit'],
    ['id_coa'=>43,'coa_name'=>'Peralatan Kantor','coa_number'=>'1.2.01.05','posisi_awal'=>'Debit'],
    ['id_coa'=>44,'coa_name'=>'Inventaris','coa_number'=>'1.2.01.06','posisi_awal'=>'Kredit'],
    ['id_coa'=>45,'coa_name'=>'Akumulasi Penyusutan Tanah','coa_number'=>'1.2.02.1','posisi_awal'=>'Kredit'],
    ['id_coa'=>46,'coa_name'=>'Akumulasi Penyusutan Bangunan','coa_number'=>'1.2.02.2','posisi_awal'=>'Kredit'],
    ['id_coa'=>47,'coa_name'=>'Akumulasi Penyusutan Kendaraan','coa_number'=>'1.2.02.3','posisi_awal'=>'Kredit'],
    ['id_coa'=>50,'coa_name'=>'Software','coa_number'=>'1.2.03.01','posisi_awal'=>'Debit'],
    ['id_coa'=>52,'coa_name'=>'Kewajiban','coa_number'=>'2.0.00','posisi_awal'=>null],
    ['id_coa'=>53,'coa_name'=>'Kewajiban Lancar','coa_number'=>'2.1.00','posisi_awal'=>null],
    ['id_coa'=>54,'coa_name'=>'Utang Usaha','coa_number'=>'2.1.01','posisi_awal'=>'Kredit'],
    ['id_coa'=>56,'coa_name'=>'Utang Pajak','coa_number'=>'2.1.03','posisi_awal'=>'Debit'],
    ['id_coa'=>65,'coa_name'=>'Utang Gaji','coa_number'=>'2.1.04.01','posisi_awal'=>'Kredit'],
    ['id_coa'=>76,'coa_name'=>'Kewajiban Tidak Lancar','coa_number'=>'2.2.00','posisi_awal'=>null],
    ['id_coa'=>78,'coa_name'=>'Utang Bank Jangka Panjang','coa_number'=>'2.2.01.01','posisi_awal'=>'Kredit'],
    ['id_coa'=>80,'coa_name'=>'Ekuitas','coa_number'=>'3.0.00','posisi_awal'=>null],
    ['id_coa'=>83,'coa_name'=>'Modal Disetor','coa_number'=>'3.1.01.01','posisi_awal'=>'Kredit'],
    ['id_coa'=>85,'coa_name'=>'Saldo Laba Ditahan','coa_number'=>'3.1.02.01','posisi_awal'=>'Kredit'],
    ['id_coa'=>89,'coa_name'=>'Pendapatan','coa_number'=>'4.0.00','posisi_awal'=>null],
    ['id_coa'=>92,'coa_name'=>'Pendapatan Jasa','coa_number'=>'4.1.01.01','posisi_awal'=>'Kredit'],
    ['id_coa'=>95,'coa_name'=>'Harga Pokok Penjualan','coa_number'=>'5.0.00','posisi_awal'=>null],
    ['id_coa'=>98,'coa_name'=>'HPP - Uang Jalan & Totalan','coa_number'=>'5.1.01.01','posisi_awal'=>'Debit'],
    ['id_coa'=>106,'coa_name'=>'Biaya','coa_number'=>'6.0.00','posisi_awal'=>null],
    ['id_coa'=>116,'coa_name'=>'Biaya Makan','coa_number'=>'6.1.01.01','posisi_awal'=>'Debit'],
    ['id_coa'=>148,'coa_name'=>'Pendapatan Lainnya','coa_number'=>'7.0.00','posisi_awal'=>null],
    ['id_coa'=>151,'coa_name'=>'Pendapatan Jasa Giro','coa_number'=>'7.1.01.01','posisi_awal'=>'Kredit'],
    ['id_coa'=>156,'coa_name'=>'Biaya Diluar Usaha','coa_number'=>'7.6.00','posisi_awal'=>null],
    ['id_coa'=>158,'coa_name'=>'Biaya Provisi Bank','coa_number'=>'7.6.01.01','posisi_awal'=>'Debit'],
    ['id_coa'=>272,'coa_name'=>'Pajak','coa_number'=>'8.0.00','posisi_awal'=>'Kredit'],
    ['id_coa'=>274,'coa_name'=>'Taksiran Pajak Penghasilan','coa_number'=>'8.1.01','posisi_awal'=>'Kredit'],
        ]);
    }
}
